sdp-tech/UPCY_Mobile

- android/app/src/main/res/values/string.xml
- android/app/src/main/res/values/strings.xml
string.xml 파일에 앱 이름을 추가해 안드로이드 환경에서 react-native 실행 시 발생하는 error: resource string/app_name 해결
> sdp-tech#2 feat : string.xml

- src/components/Home/Market/DetailBox.tsx
- src/components/Home/Market/DetailPage.tsx
- src/components/Home/Market/OptionBox.tsx
탭뷰 추가 및 연결되는 컴포넌트 추가(중복 예상 시 추후 삭제 예정)
> sdp-tech#14 feat : product detail page with tabview

- ios/Podfile.lock
- ios/upcy.xcodeproj/project.pbxproj
- src/components/Home/Market/GoodsDetailPage.tsx
- src/pages/Home.tsx
- yarn.lock
1. 상품 디테일 페이지
- 화면 상단 수정
- 임시 이미지 삽입
- 텍스트 크기 조정
- 색상 및 기타 다양한 사항 조정
2. 홈 화면 수정
- 클릭하기 편하게 버튼 형식으로 변경 only
> #14 feat: reformed GoodsDetailPage, Home

- android/app/src/main/AndroidManifest.xml
- ios/Podfile.lock
- ios/upcy.xcodeproj/project.pbxproj
- package.json
- src/common/FileBox.tsx
- src/common/FilePicker.tsx
- src/common/PeriodPicker.tsx
- src/common/PhotoOptions.tsx
- src/components/Auth/BasicForm.tsx
- src/components/Auth/Reformer/CareerModal.tsx
- src/components/Auth/Reformer/EducationModal.tsx
- src/components/Auth/Reformer/ReformFormCareer.tsx
- src/components/Auth/Reformer/ReformFormProfile.tsx
- src/components/Auth/Reformer/ReformFormStyle.tsx
- src/components/Auth/Reformer/Reformer.tsx
- src/types/UserTypes.ts
- yarn.lock
* image-picker 연결
* 프로필 사진 업로드 구현
* document-picker 연결
* 파일 업로드 상세 조건 확인 후 추가 / 삭제 핸들링 구현 필요
> #8 feat: add extra input fields

- ios/Podfile.lock
- ios/upcy.xcodeproj/project.pbxproj
- src/components/Home/Market/GoodsDetailPage.tsx
- src/components/Home/Market/GoodsRegistration.tsx
- src/components/Home/Market/ServiceRegistration.tsx
- src/components/Home/Market/TempStorage.tsx
- src/components/Home/Market/TempStorageEdit.tsx
1. 상품 등록, 서비스 등록, 상품 페이지, 임시저장 페이지, 임시수정 페이지 UI 수정
2. 임시수정 페이지에 전체선택 및 전체 삭제, 선택 삭제 기능 구현 완료
> #14 feat : Select/delete logic, fixed UI

- ios/Podfile.lock
- ios/upcy.xcodeproj/project.pbxproj
- src/common/Hashtag.tsx
- src/common/InputBox.tsx
- src/components/Home/Market/FilterElement.tsx
- src/components/Home/Market/GoodsRegistration.tsx
- src/components/Home/Market/ServiceRegistration.tsx
1. 해시태그 기능 완성
2. 가격, 디테일 리스트 추가 기능 구현
3. 상품등록, 서비스등록 페이지 UI 완성 단계 (바텀바 문제 해결 필요)
> #14 feat :added hashtag logic, detailList logic. fixed page UIs

- src/components/Home/Portfolio/AddPortfolio.tsx
- src/components/Home/Portfolio/PortfolioSubmit.tsx
- src/components/Home/Portfolio/PortfolioWrite.tsx
* 작성 완료 페이지 구현 후 연결 (임시)
* 임시 저장 페이지 연결
* 이미지 등록 컴포넌트 수정
> #61 feat: add additional portfolio pages

- ios/Podfile.lock
- src/common/ImageCarousel.tsx
- src/common/Slider.tsx
- src/components/Home/Portfolio/PortfolioWrite.tsx
- src/hooks/useImagePicker.ts
- yarn.lock
* 이미지 첨부를 위한 캐러셀 컴포넌트 구현 (피그마상으로 상세화면 컴포넌트 - 이미지 등록 박스)
> #61 feat: add ImageCarousel component

- src/components/Auth/BasicForm.tsx
- src/components/Auth/Login.tsx
- src/components/Auth/Reformer/ReformFormCareer.tsx
- src/types/UserTypes.ts
* 로그인, 기본 가입, 리포머 프로필 등록, 경력 등록 api 연결
* 기본적인 에러 처리 구현
* 로그인 토큰 관리
* 요청 후 콜백 구현 (실패 / 성공시)
> #72 feat: connect users api

- App.tsx
- ios/Podfile.lock
- ios/upcy.xcodeproj/project.pbxproj
- src/common/Context.tsx
- src/components/Auth/Login.tsx
- src/hooks/useLoginGuard.ts
- src/pages/MyPage.tsx
* 로그인 api 연결 및 테스트 (현재 임시 유저로 로그인 가능)
* 로그인 토큰 관리
* 로그인 후 마이페이지 확인 가능
* 마이페이지에서 로그아웃 가능
* 회원가입 api 연결
> #72 feat: set login flow

- App.tsx
- src/common/requests.js
- src/components/Auth/BasicForm.tsx
- src/components/Home/Market/WriteReviewPage.tsx
- src/pages/ComponentsTest.tsx
- src/pages/Home.tsx
- src/pages/MyPage.tsx
- yarn.lock
* 로그인 및 기본 가입 api 테스트 완료
* 도메인 변경 시도했으나 http 연결 문제로 아직 테스트 불가 (https 설정 이후 재변경 예정)
> #78 feat: set users login, signup api

- ios/Podfile.lock
- ios/upcy.xcodeproj/project.pbxproj
- src/assets/common/Top.svg
- src/common/ImageCarousel.tsx
- src/common/ScrollToTopButtonFlat.tsx
- src/common/ScrollTopButton.tsx
- src/components/Home/HomeMain.tsx
- src/components/Home/Market/DetailBox.tsx
- src/components/Home/Market/FilterElement.tsx
- src/components/Home/Market/MarketTabView.tsx
- src/components/Home/Market/OptionBox.tsx
- src/components/Home/Market/ReviewPage.tsx
- src/components/Home/Market/Reviews.tsx
- src/components/Home/Market/ServiceDetailPage.tsx
- src/components/Home/Market/ServicePage.tsx
- src/components/Home/Market/ServiceRegistration.tsx
- src/components/Home/Market/WriteDetailPage.tsx
- src/components/Home/Market/WriteReviewPage.tsx
- src/components/Home/components/ServiceCategoryModal.tsx
- src/pages/Home.tsx
- yarn.lock
1. 이미지 캐로셀 수정 (기존에 사용되던 것들에는 문제 없도록 수정했습니다): originalSize 등의 프로퍼티 추가했습니다. 쭉 보시면 아실겁니다
2. 서비스 등록 페이지 완성: 가. 이미지 삽입 기능 완성, 나. 이미 등록한 옵션 수정 기능 완성, 다. 서비스 상세 작성 페이지와 네비게이팅 연결 완료
3. 서비스 상세 작성 페이지 완성
> #14/feat/ImageCarousel,ServiceRegistrationPage,WriteDetailPage

- src/components/Home/HomeMain.tsx
Pull request #86 병합 중 컨플릭트 해결하면서 잘못 올라간 부분이 있어 수정했습니다.
> fix: fix error from resolving conflicts

- node_modules/react-native/index.js
- package.json
- src/common/FileBox.tsx
- src/common/FilePicker.tsx
- src/common/InputView.tsx
- src/components/Auth/BasicForm.tsx
- src/components/Auth/Reformer/CareerModal.tsx
- src/types/UserTypes.ts
- yarn.lock
* 비밀번호 조건 설정 및 검증
* 파일 업로드 조건 설정 및 테스트 진행
> #78 feat: validate onboarding

- App.tsx
- ios/Podfile.lock
- ios/upcy.xcodeproj/project.pbxproj
- node_modules/react-native/index.js
- src/pages/FixMyPage.tsx
- src/pages/Home.tsx
- src/pages/MyPage.tsx
- src/pages/OrderPage.tsx
- yarn.lock
1. 마이페이지 작성
2. 주문 탭 작성
3. 마이페이지 수정 페이지 작성
4. 수정페이지와 마이페이지 연결 완료
> #91/feat//MyPage, FixMyPage

- ios/Podfile.lock
- package-lock.json
- package.json
- src/pages/FixMyPage.tsx
- src/pages/MyPage.tsx
- yarn.lock
의존성 문제 해결했습니다. 
(npm install)
마이페이지 유저 프로필 조회 api 작성했습니다 (연결은 아직입니다)
> #91 fix: dependency problem, api connect test

- App.tsx
- src/common/Context.tsx
- src/common/CustomScrollView.tsx
- src/common/InputView.tsx
- src/common/SignUpCompleteModal.tsx
- src/components/Auth/BasicForm.tsx
- src/components/Auth/Login.tsx
- src/components/Auth/Reformer/CareerModal.tsx
- src/components/Auth/Reformer/EducationModal.tsx
- src/components/Auth/Reformer/ReformFormCareer.tsx
- src/components/Auth/Reformer/ReformFormProfile.tsx
- src/components/Auth/Reformer/ReformFormSubmit.tsx
- src/components/Auth/Reformer/Reformer.tsx
- src/components/Auth/SignIn.tsx
- src/components/Auth/Signup.tsx
- src/components/Auth/Upcyer/Upcyer.tsx
- src/components/Home/components/DetailScreenHeader.tsx
- src/types/UserTypes.ts
회원가입 플로우 전면 수정 완료 (UI)
- API 테스트 필요
> feat/81/회원가입 플로우 전면 수정

- App.tsx
- src/common/Context.tsx
- src/common/requests.js
- src/common/storage.js
- src/components/Auth/BasicForm.tsx
- src/components/Auth/Login.tsx
- src/components/Auth/Reformer/ReformFormCareer.tsx
- src/components/Auth/Signup.tsx
- src/components/Auth/Upcyer/Upcyer.tsx
- src/pages/FixMyPage.tsx
- src/pages/MyPage.tsx
1. api 코드 수정했습니다. (도메인 변경, 기타 등등...)
-> api 연결 코드는 Login.tsx 페이지나, FixMyPage.tsx 참고하시면 구조 파악하시기 편하실겁니다! 
2. 로그인, 로그아웃 로직 수정 완료했습니다. 노션에 올린 테스트 이메일과 비밀번호로 로그인 가능합니다. 로그아웃은 마이페이지 -> 편집에서 가능합니다. 
3. 리폼러 회원가입 플로우 약간 수정했습니다. (더 할 예정)
> feat/118/fixed request.js, Login, Logout

- src/components/Home/HomeMain.tsx
- src/components/Home/Market/Service.tsx
- src/pages/Home.tsx
- src/types/UserTypes.ts
* Refactored codes.
* Added the functionality of the existing filter- to sort by price in ascending order.
> #126 feat : add price sorting logic to home screen

- src/common/CustomHeader.tsx
- src/components/Home/HomeMain.tsx
- src/components/Home/Market/FilterElement.tsx
- src/components/Home/Market/GoodsDetailPage.tsx
- src/components/Home/Market/Service.tsx
- src/components/Home/Market/ServiceDetailPage.tsx
- src/components/Home/components/ServiceItem.tsx
- src/components/Home/components/StyleFilterButton.tsx
- src/pages/Home.tsx
* refactored the ServiceCard component
* added the styles filter UI
* routed the first page ServiceCard components to ServiceDetailPage
* refactored codes
* added minor UI
> #126 feat : fix first page

- src/components/Home/Market/ServiceDetailPage.tsx
- src/components/Home/Quotation/QuotationConfirm.tsx
- src/pages/Home.tsx
* show review page at service detail page
* navigation bug fix
> minor edits

- src/components/Home/Market/market-api.js
일단 틀만 만들었는데 여기에 market 관련 api 함수 다 모아서 정리하면 될 것 같습니다!
지금 token 관련 문제가 있어 코드 더 봐야 합니다.. ㅜ
> market-api.js 파일

- App.tsx
- src/components/Auth/BasicForm.tsx
- src/components/Auth/Login.tsx
- src/components/Auth/Reformer/Profile/Service.tsx
- src/components/Auth/SignIn.tsx
- src/components/Auth/Upcyer/Upcyer.tsx
- src/components/Home/Market/InfoPage.tsx
- src/components/Home/Market/Service.tsx
- src/components/Home/components/DetailScreenHeader.tsx
- src/components/Home/components/ServiceItem.tsx
- src/pages/FixMyPage.tsx
- src/pages/MyPage.tsx
- yarn.lock
1. 로그인 관련 오류 해결 (이제 무조건 아이디 비밀번호 입력해야만 들어가집니다)
2. 마이페이지 UI 수정
3. Upcyer로 회원가입 시, 자꾸 route.params에서 오류나서 해결중인데...잘 안 되네요...
4. 전체 서비스 get하는 코드 작성하다 말았습니다... 힘드네요... 제가 ServiceRegiPage에 작성해둔 것처럼, response도 잘 쪼개서 ServiceCard 컴포넌트에 넣으면 될 듯합니다.
> #132 fix: minor fixes, service api(ing)

- src/common/Context.tsx
- src/components/Home/HomeMain.tsx
- src/components/Home/Market/Service.tsx
- src/components/Home/components/HomeStyleFilterElement.tsx
- src/components/Home/components/ServiceItem.tsx
- src/pages/Home.tsx
* login logic minor fix
* home filter button functionality fix
* 기타
> minor code fix

- src/components/Home/Market/DetailBox2.tsx
- src/components/Home/Market/MarketTabView.tsx
- src/components/Home/Market/Service.tsx
- src/components/Home/Market/ServiceDetailPage.tsx
- src/components/Home/components/CustomReportButton.tsx
- src/components/Home/components/DetailScreenHeader.tsx
- src/pages/Home.tsx
* 1차 버전에 들어가지 않는 UI 모두 주석 처리
* 1차 버전 용 UI 구현- 신고 버튼, service page, reformer page 등
* API 주소 수정사항에 따른 코드 수정
* 서비스 상세 페이지 api 연결하여 수정
> minor edits & service detail page ui with api connected

- App.tsx
- src/common/CustomHeader2.tsx
- src/common/Footer.tsx
- src/components/Auth/Reformer/Reformer.tsx
- src/components/Auth/Reformer/ReformerMyPage.tsx
- src/components/Home/Market/DetailBox2.tsx
- src/components/Home/Market/MarketTabView.tsx
- src/components/Home/Market/Service.tsx
- src/components/Home/Market/ServiceDetailPage.tsx
- src/components/Home/components/ReformerTag.tsx
- src/pages/Home.tsx
- src/pages/MyPage.tsx
- src/pages/SearchPage.tsx
* Service Card
* Detail Box
* Scrolling
* Footer
* Labeling
* Search box searching function
UI fix & add
> Service & Market relevant pages, custom header, home UI

- App.tsx
- src/common/Context.tsx
- src/common/storage.js
- src/components/Auth/Login.tsx
- src/components/Auth/Reformer/ReformFormCareer.tsx
- src/components/Auth/Reformer/ReformerMyPage.tsx
- src/components/Auth/Upcyer/UpcyerMyPage.tsx
- src/components/Home/Market/ServicePage.tsx
- src/pages/Home.tsx
- src/pages/MyPage.tsx
- src/pages/ReportPage.tsx
유저롤... 로그인때만 상태관리해서... 하단탭 렌더링하도록...
그리고 로그아웃시 유저롤 customer로 설정...
그 외 다양한 디버깅
> #116: UserRole settings

- src/components/Auth/Reformer/ReformerMyPage.tsx
- src/components/Home/Market/ServiceRegistration.tsx
- src/components/Home/Market/TempStorage.tsx
> TempStorage UI & Features

- src/components/Auth/BasicForm.tsx
- src/components/Auth/Reformer/CareerModal.tsx
- src/components/Auth/Reformer/ReformFormCareer.tsx
- src/components/Auth/Reformer/ReformerMyPage.tsx
- src/components/Home/Market/Service.tsx
- src/components/Home/Market/ServiceRegistration.tsx
- src/components/Home/Market/TempStorage.tsx
- src/pages/Home.tsx
- src/pages/MyPage.tsx
- src/pages/SearchPage.tsx
- src/types/UserTypes.ts
- type errors in tempstorage, etc....
- code refactor
- zIndex in Home.tsx
- file upload API connected (not perfect yet)
> #116: fix error, code refactor, File upload API (not perfect yet)

- src/common/FileBox.tsx
- src/common/Footer.tsx
- src/components/Auth/Reformer/CareerModal.tsx
- src/components/Auth/Reformer/ReformFormCareer.tsx
- src/components/Auth/Reformer/ReformerMyPage.tsx
- src/components/Home/Market/DetailBox2.tsx
- src/components/Home/Market/InfoPage.tsx
- src/components/Home/Market/MarketTabView.tsx
- src/components/Home/Market/Service.tsx
- src/components/Home/Market/ServiceDetailPage.tsx
- src/components/Home/Market/ServiceRegistration.tsx
- src/components/Home/Market/WriteDetailPage.tsx
- src/pages/Home.tsx
- src/types/UserTypes.ts
1. 자격증명 파일 업로드는 아마 되는 것 같습니다만... uri에 문제가 조금 있는 것 같아서, 수정이 필요한 상황입니다. 
2. InfoPage에 들어갈 marketData의 MarketType을 추가했습니다. 기존 MarketResponseType만으로는 모자라는 상황들이 발생해서 그렇습니다... 
3. 리포머가 본인의 마켓 정보, 리포머 정보를 이제 잘 볼 수 있습니다!! 
4. 프로필 수정 시에, 경력사항들이 제대로 수정되지 않던 문제 해결했습니다
> #118: fix: uploadFiles(but have one error), refactor: InfoPage, add: MarketType

- App.tsx
- src/common/Footer.tsx
- src/common/Slider.tsx
- src/components/Auth/Login.tsx
- src/components/Auth/Reformer/ReformFormCareer.tsx
- src/components/Auth/Reformer/ReformerMyPage.tsx
- src/components/Home/Market/DetailBox2.tsx
- src/components/Home/Market/InfoPage.tsx
- src/components/Home/Market/MarketTabView.tsx
- src/components/Home/Market/Service.tsx
- src/components/Home/Market/ServiceDetailPage.tsx
- src/components/Home/Market/ServicePage.tsx
- src/components/Home/Market/ServiceRegistration.tsx
- src/components/Home/Market/WriteDetailPage.tsx
- src/components/Home/Order/CompletedOrders.tsx
- src/components/Home/Order/OrderManagement.tsx
- src/pages/FixMyPage.tsx
- src/pages/Home.tsx
- src/types/UserTypes.ts
- tsconfig.json
1. 로그인, 로그아웃 과정에서 marketUUID 관리하는 로직 약간 수정했습니다
2. 서비스 등록할 때, 옵션별 사진이나 서비스 상세 안에 들어가는 사진들 잘 올라갑니다
3. 홈화면 전체 서비스에서, (Service.tsx) 수정 많이 했습니다. 서비스 상세 안에 있는 사진도 받아오고, 옵션별 사진도 받아오도록 수정했습니다 (이건 테스트 필요)
4. 리폼러 마이페이지에서: 기존 마켓쪽 api가 잘 작동 안하는게 있어서, 리포머 api로 많이 변경했습니다 
5. 안드로이드 스튜디오에서 작업하시는 분들도 타입 에러 잘 잡도록 tsconfig 수정했습니다 반드시 풀 받아주세요! 
6. 그 외에도 이것저것 수정한게 많은데... 정신없이 작업하다보니 어디어디 하고있는지 보고를 못 했네요... merge conflict 많으면...죄송합니다...
> #132 feat: ServiceDetailPage: service_images

- src/components/Auth/BasicForm.tsx
- src/components/Auth/Login.tsx
- src/components/Auth/Reformer/ReformFormCareer.tsx
- src/components/Auth/Reformer/ReformerMyPage.tsx
- src/components/Home/Market/InfoPage.tsx
- src/components/Home/Market/MarketTabView.tsx
- src/components/Home/Market/Service.tsx
- src/components/Home/Market/ServicePage.tsx
- src/types/UserTypes.ts
엔드포인트 맞춰서 에러처리 코드 추가했습니다
이제 리포머프로필 수정하고 나면 스택 초기화되고 홈으로 갑니다. 
리포머 정보 받아오는 로직도 조금 수정했습니다.
> fix some endpoint codes, ReformerMypage, Service flow.

- src/components/Auth/Reformer/ReformerMyPage.tsx
- src/components/Home/Market/ServicePage.tsx
- src/components/Home/Market/ServiceRegistration.tsx
- src/components/Home/Market/TempStorage.tsx
임시저장 버튼: 리폼러 마이페이지에서 보입니다 
그거 누르면 목록 넘어가고 (해담솔님이 만들어주심) 
서비스 등록 페이지까지 잘 넘어갑니다. 
그리고 임시저장서비스 삭제로직에 오류있어서 수정했습니다.
> feat TempStorage button, connecting between TempStorage <-> ServiceRegistrationPage

- package-lock.json
- src/common/BottomButton.tsx
- src/common/Footer.tsx
- src/components/Home/Order/CompletedOrders.tsx
- src/components/Home/Order/InProgressOrders.tsx
- src/components/Home/Order/NewOrders.tsx
- src/components/Home/Quotation/InputInfo.tsx
- src/components/Home/Quotation/QuotationConfirm.tsx
- src/components/Home/Quotation/QuotationForm.tsx
- src/components/Home/Quotation/QuotationPage.tsx
- src/components/Home/Quotation/Rejection.tsx
- yarn.lock
주문서 생성 api 연결 했으나, 아직 주문서 생성 오류 납니다.
주문서 관련 다수 수정했습니다
> Orderupdate

- App.tsx
- ios/upcy/Info.plist
- src/components/Auth/Login.tsx
- src/components/Home/Market/ServiceDetailPage.tsx
- src/pages/MyPage.tsx
1. 로그인 페이지 ui 수정했습니다. 
2. 로그인 페이지, 마이페이지에 로딩상태 추가했습니다.
> #116: fixed UI in LoginPage, added indicators

- src/common/Context.tsx
- src/common/CustomHeader2.tsx
- src/common/FileBox.tsx
- src/components/Auth/Reformer/ReformFormCareer.tsx
- src/components/Home/Market/MarketTabView.tsx
- src/components/Home/Market/Service.tsx
- src/components/Home/Market/ServiceDetailPage.tsx
- src/components/Home/Order/OrderManagement.tsx
- src/components/Home/components/ReformerTag.tsx
1. 로그인 부분에서, 액세스토큰 저장하는 로직 수정했습니다 (배포용) -> 디버깅 하실때에 액세스토큰 남아있어서 회원가입 테스트 불가능하실 때에는, 로그인 창의 test 버튼 누르시면 토큰 삭제됩니다. 
2. 마켓탭뷰 (리포머 프로필) ui 수정했습니다. 
3. 파일 업로드 로직 수정해서 이제 잘 됩니다. 
4. 검색 페이지 ui 터치되게 바꿨습니다. 
5. 서비스디테일페이지 오류 다량 수정했습니다. (담솔님이 추가 수정하실 필요 있으십니다 파이팅)
> #116: fix many things

- src/components/Auth/Login.tsx
- src/components/Home/Market/InfoPage.tsx
- src/components/Home/Market/MarketTabView.tsx
- src/components/Home/Market/ServiceDetailPage.tsx
- src/pages/ReportPage.tsx
1. 신고 페이지 연결 조금 수정했습니다. (식별자 포함)
2. 리폼러 페이지에서, InfoPage에 있는 링크 누르면 safari 켜집니다.
> #116 fix, feat: ReportPage, Linking

- src/components/Home/Market/ServiceDetailPage.tsx
- src/components/Home/Market/ServicePage.tsx
- src/components/Home/Market/ServiceRegistration.tsx
- src/components/Home/Market/TempStorage.tsx
- src/components/Home/Market/WriteDetailPage.tsx
> fix: Resolve issue in service handling

- .gitignore
- ios/upcy.xcodeproj/project.pbxproj
- ios/upcy/Info.plist
- src/common/PhotoOptions.tsx
- src/common/SplashScreen.tsx
- src/common/navigationUtils.ts
- src/common/requests.js
- src/components/Auth/Login.tsx
- src/components/Auth/Reformer/ReformFormCareer.tsx
- src/components/Auth/Reformer/ReformerMyPage.tsx
- src/components/Home/Market/DetailBox.tsx
- src/components/Home/Market/DetailBox2.tsx
- src/components/Home/Market/MarketTabView.tsx
- src/components/Home/Market/Service.tsx
- src/components/Home/Market/ServiceDetailPage.tsx
- src/components/Home/Market/ServicePage.tsx
- src/components/Home/Market/ServiceRegistration.tsx
- src/components/Home/Market/TempStorage.tsx
- src/components/Home/Market/WriteDetailPage.tsx
- src/components/Home/Quotation/QuotationForm.tsx
- src/pages/Home.tsx
- src/pages/MyPage.tsx
- src/pages/ReportPage.tsx
- src/pages/SearchPage.tsx
1. 신고 기능 완성....!!! 
2. 서비스 등록시에, 사진 올라갑니다.. 근데 수정해야해요 백엔드도 수정됐어요
3. 서비스 상세 작성 페이지 들어갔다 나와도 이제 데이터 잘 유지됩니다 ! 
4. 근데 서비스 수정은... 수정이 아니라 새롭게 등록돼버리네요 ㅠㅠ..
> #116 refactor: ReportPage, ServiceRegi

- package-lock.json
- package.json
- src/common/requests.js
- src/components/Home/Order/InProgressOrders.tsx
- src/components/Home/Order/NewOrders.tsx
- src/components/Home/Order/OrderManagement.tsx
- src/components/Home/Quotation/QuotationConfirm.tsx
- yarn.lock
order_status
<거래전, 수락완료, 수령 완료, 제작 중, 제작 완료> 까지 작업 
배송 중 (오류납니다..._
> order_status
